# Generated by Django 4.2.7 on 2023-11-16 07:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacture_No', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Process_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('process_type', models.CharField(max_length=200)),
                ('process_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=200)),
                ('process_id', models.ManyToManyField(to='urban_app.process_details')),
            ],
        ),
        migrations.CreateModel(
            name='process_update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('time', models.TimeField(default=datetime.time(0, 0))),
                ('issues', models.TextField()),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('On Going', 'On Going'), ('Not Started', 'Not Started'), ('Issue Raised', 'Issue Raised')], default='Not Started', max_length=200)),
                ('manufacture_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urban_app.manufacture')),
                ('process_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urban_app.process_details')),
            ],
        ),
        migrations.AddField(
            model_name='manufacture',
            name='model_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urban_app.product_model'),
        ),
    ]
