# Generated by Django 4.2.7 on 2023-11-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urban_app', '0002_alter_process_update_issues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_update',
            name='end_date',
            field=models.DateField(default=True),
        ),
        migrations.AlterField(
            model_name='process_update',
            name='start_date',
            field=models.DateField(default=True),
        ),
    ]
