# Generated by Django 4.2.7 on 2023-11-16 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urban_app', '0003_alter_process_update_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_update',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='process_update',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
